include: package:lints_tool/lints_tool.yaml

analyzer:
  exclude:
    # Codegen
    - "lib/core/gen/**"
    # Tools
    - "tool/google_localizer/**"
    - "tool/setup_clone/**"
    - "tool/grind.dart"
    # App
    - "lib/core/constant/*_icons.dart"
    - "lib/core/constant/*_strings.dart"
