targets:
  $default:
    sources:
      - $package$
      - pubspec.yaml
      - lib/**
      - test/**
    builders:
      json_serializable:
        options:
          checked: true
          field_rename: snake
      pubspec_generator:
        options:
          output: lib/_core/generated/constant/pubspec.yaml.g.dart
      drift_dev:
        generate_for:
          include:
            - lib/_core/database/**
        # options:
        #   data_class_to_companions: true
        #   mutable_classes: false
        #   sqlite:
        #     version: "3.41"
