targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
          
      json_serializable:
        enabled: true
        generate_for:
          - lib/src/**
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          ignore_unannotated: false
          include_if_null: true

      auto_route_generator:autoRouteGenerator:
        enabled: true
        generate_for:
          - lib/src/**
