name: ui_tool

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

  # Packages
  core_tool:
    path: ../core_tool

  # SDK extensions
  collection: any
  characters: ^1.3.0
  meta: any
  uuid: any

  # Internationalization
  intl: any

dev_dependencies:
  lints_tool:
    path: ../../tool/lints_tool

flutter:
  uses-material-design: true
