name: auth_model
resolution: workspace

description: Authentication model

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  # Packages
  core_model:
    path: ../../model/core_model
  connect_model:
    path: ../../model/connect_model
  http_client:
    path: ../../model/http_client

  # SDK extensions
  meta: any
  fixnum: any
  # crypto: any

  # Internationalization
  intl: any

  # Code generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

  # API
  connectrpc: ^1.0.0
  protobuf: ^6.0.0

dev_dependencies:
  # Code generation
  build_runner: ^2.16.0
  freezed: ^4.0.0-dev.3
  json_serializable: ^6.14.1

  # Tests
  flutter_test:
    sdk: flutter
  http: ^1.6.0

  # Lints
  lints_tool:
    path: ../../tool/lints_tool
