/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9CBsBgzJ4c07YEK2hKBv48rAeBNOwIwQ',
    appId: '1:18736676875:web:81e99c4b04da97fe87870e',
    messagingSenderId: '18736676875',
    projectId: 'zs-auth-app',
    authDomain: 'zs-auth-app.firebaseapp.com',
    storageBucket: 'zs-auth-app.firebasestorage.app',
    measurementId: 'G-Q1S9FHJJGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmrzH95Ex5xyNHkoCnVGC9cgqUToZn028',
    appId: '1:18736676875:android:29ce1b60c5a33d3d87870e',
    messagingSenderId: '18736676875',
    projectId: 'zs-auth-app',
    storageBucket: 'zs-auth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnYmWkKoRiNdX7QKVKLOS6faO2z8SbADU',
    appId: '1:18736676875:ios:5edcdd1ea9a7393787870e',
    messagingSenderId: '18736676875',
    projectId: 'zs-auth-app',
    storageBucket: 'zs-auth-app.firebasestorage.app',
    iosBundleId: 'app.dmitrii.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnYmWkKoRiNdX7QKVKLOS6faO2z8SbADU',
    appId: '1:18736676875:ios:5edcdd1ea9a7393787870e',
    messagingSenderId: '18736676875',
    projectId: 'zs-auth-app',
    storageBucket: 'zs-auth-app.firebasestorage.app',
    iosBundleId: 'app.dmitrii.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9CBsBgzJ4c07YEK2hKBv48rAeBNOwIwQ',
    appId: '1:18736676875:web:9f70ad50fdc41c5887870e',
    messagingSenderId: '18736676875',
    projectId: 'zs-auth-app',
    authDomain: 'zs-auth-app.firebaseapp.com',
    storageBucket: 'zs-auth-app.firebasestorage.app',
    measurementId: 'G-0CXSZ4SKF0',
  );

}
*/
